PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fam: <http://www.teamofteams.nl/ontologies/fam/1>


SELECT ?s ?p ?o ?l
WHERE {
#    ?s a fam:Person # this should work when inferencing is enabled
    ?s rdf:type ?o .
    ?o rdfs:subClassOf fam:Person
}